# Generated by Django 5.1.7 on 2025-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_promotion_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='./hoodie.png', max_length=255),
            preserve_default=False,
        ),
    ]
