# Generated by Django 5.1.7 on 2025-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
