# Generated by Django 5.1.7 on 2025-04-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='id_product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='id_product',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
