# Generated by Django 5.1.7 on 2025-04-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_promotion_id_product_size_id_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
