# Generated by Django 5.1.7 on 2025-04-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
